import Foundation

/// Well-known representation type identifiers. These are UTIs on Apple platforms; other platforms
/// map their native clipboard formats onto the same identifiers so stored clips stay portable.
public enum RepresentationType {
    public static let plainText = "public.utf8-plain-text"
    public static let utf16PlainText = "public.utf16-external-plain-text"
    public static let rtf = "public.rtf"
    public static let rtfd = "com.apple.flat-rtfd"
    public static let html = "public.html"
    public static let url = "public.url"
    public static let urlName = "public.url-name"
    public static let fileURL = "public.file-url"
    public static let png = "public.png"
    public static let tiff = "public.tiff"
    public static let jpeg = "public.jpeg"
    public static let heic = "public.heic"
    public static let gif = "com.compuserve.gif"
    public static let webp = "org.webmproject.webp"
    public static let pdf = "com.adobe.pdf"
    public static let color = "com.apple.cocoa.pasteboard.color"
    public static let webArchive = "com.apple.webarchive"

    /// nspasteboard.org conventions used by password managers and other privacy-aware apps.
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let transient = "org.nspasteboard.TransientType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    public static let sourceMarker = "org.nspasteboard.source"

    public static let imageTypes: [String] = [png, tiff, jpeg, heic, gif, webp]

    /// Types worth persisting, in restore-priority order. Anything else is kept only when small.
    public static let preferred: [String] = [
        fileURL, url, urlName, plainText, rtf, rtfd, html, png, tiff, jpeg, heic, gif, webp, pdf, color, webArchive,
    ]

    /// Types that are never persisted because they are markers, redundant or not restorable.
    public static func isIgnored(_ type: String) -> Bool {
        if type.hasPrefix("dyn.") { return true }
        if type == concealed || type == transient || type == autoGenerated || type == sourceMarker { return true }
        if type.hasPrefix("com.apple.pasteboard.promised") { return true }
        if type.hasPrefix("com.apple.NSFilePromise") { return true }
        if type == "com.apple.icns" { return true }
        if type.hasPrefix("CorePasteboardFlavorType") { return true }
        if type.hasPrefix("Apple ") || type.hasPrefix("NeXT ") || type.hasPrefix("NS") { return true }
        if type == utf16PlainText { return true }
        return false
    }
}

/// A platform-neutral capture of the clipboard at one moment in time. Platform monitors build
/// one of these; `CaptureProcessor` decides what (if anything) gets stored.
public struct ClipboardSnapshot: Sendable {
    public var items: [[ClipRepresentation]]
    /// All type identifiers present on the clipboard, including ones not loaded into `items`.
    public var declaredTypes: Set<String>
    public var sourceApp: SourceApplication?
    public var capturedAt: Date
    public var hints: Hints

    /// Facts the platform layer can compute cheaply and the core cannot (because they need
    /// platform APIs such as color decoding or file-system checks).
    public struct Hints: Sendable, Hashable {
        public var colorHex: String?
        public var imagePixelSize: (width: Int, height: Int)?
        public var directoryPaths: Set<String>
        public var pdfPageCount: Int?

        public init(colorHex: String? = nil, imagePixelSize: (width: Int, height: Int)? = nil,
                    directoryPaths: Set<String> = [], pdfPageCount: Int? = nil) {
            self.colorHex = colorHex
            self.imagePixelSize = imagePixelSize
            self.directoryPaths = directoryPaths
            self.pdfPageCount = pdfPageCount
        }

        public static func == (lhs: Hints, rhs: Hints) -> Bool {
            lhs.colorHex == rhs.colorHex && lhs.imagePixelSize?.width == rhs.imagePixelSize?.width
                && lhs.imagePixelSize?.height == rhs.imagePixelSize?.height
                && lhs.directoryPaths == rhs.directoryPaths && lhs.pdfPageCount == rhs.pdfPageCount
        }

        public func hash(into hasher: inout Hasher) {
            hasher.combine(colorHex)
            hasher.combine(imagePixelSize?.width)
            hasher.combine(imagePixelSize?.height)
            hasher.combine(directoryPaths)
            hasher.combine(pdfPageCount)
        }
    }

    public init(items: [[ClipRepresentation]], declaredTypes: Set<String>? = nil, sourceApp: SourceApplication?,
                capturedAt: Date = Date(), hints: Hints = Hints()) {
        self.items = items
        self.declaredTypes = declaredTypes ?? Set(items.flatMap { $0.map(\.type) })
        self.sourceApp = sourceApp
        self.capturedAt = capturedAt
        self.hints = hints
    }

    /// Convenience for tests and simple producers: a single-item snapshot.
    public static func single(_ reps: [String: Data], source: SourceApplication? = nil, hints: Hints = Hints()) -> ClipboardSnapshot {
        let ordered = reps.sorted { lhs, rhs in
            (RepresentationType.preferred.firstIndex(of: lhs.key) ?? .max) < (RepresentationType.preferred.firstIndex(of: rhs.key) ?? .max)
        }
        return ClipboardSnapshot(items: [ordered.map { ClipRepresentation(itemIndex: 0, type: $0.key, data: $0.value) }],
                                 sourceApp: source, hints: hints)
    }

    public static func text(_ string: String, source: SourceApplication? = nil) -> ClipboardSnapshot {
        single([RepresentationType.plainText: Data(string.utf8)], source: source)
    }

    public var allRepresentations: [ClipRepresentation] { items.flatMap { $0 } }

    public func first(_ type: String) -> Data? {
        for item in items { if let rep = item.first(where: { $0.type == type }) { return rep.data } }
        return nil
    }

    public func all(_ type: String) -> [Data] {
        items.compactMap { item in item.first(where: { $0.type == type })?.data }
    }

    public var plainText: String? {
        let strings = all(RepresentationType.plainText).compactMap { String(data: $0, encoding: .utf8) }
        guard !strings.isEmpty else { return nil }
        return strings.joined(separator: "\n")
    }

    public var fileURLs: [URL] {
        all(RepresentationType.fileURL).compactMap { data in
            guard let raw = String(data: data, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines) else { return nil }
            guard let url = URL(string: raw), url.isFileURL else { return nil }
            return url.standardizedFileURL
        }
    }

    public var isConcealed: Bool { declaredTypes.contains(RepresentationType.concealed) }
    public var isTransient: Bool { declaredTypes.contains(RepresentationType.transient) }
    public var isAutoGenerated: Bool { declaredTypes.contains(RepresentationType.autoGenerated) }

    public var imageData: (type: String, data: Data)? {
        for type in RepresentationType.imageTypes {
            if let data = first(type) { return (type, data) }
        }
        return nil
    }

    public var totalByteSize: Int64 { allRepresentations.reduce(0) { $0 + Int64($1.data.count) } }
}
